name: movies_redux
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.3
  built_value: ^8.1.0
  built_collection: ^5.1.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_epics: ^0.15.0
  freezed_annotation: ^0.14.2
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  image_picker: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  built_value_generator: ^8.1.0
  freezed: ^0.14.2

dependency_overrides:
  rxdart: ^0.27.1


flutter:
  uses-material-design: true
